timeout: 1800s

steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    secretEnv: [ 'APP_TOKEN', 'CLIENT_ID', 'GUILD_ID', 'PROXY_URL']
    args:
      [ '-c',
        "docker build
          --build-arg APP_TOKEN=$$APP_TOKEN
          --build-arg CLIENT_ID=$$CLIENT_ID
          --build-arg GUILD_ID=$$GUILD_ID
          --build-arg PROXY_URL=PROXY_URL
          -t ${_IMAGE_NAME}
          ."
      ]
    id: 'build-image'
    timeout: 600s

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', '${_IMAGE_NAME}' ]
    id: 'push-image'
    timeout: 600s
    waitFor: [ 'build-image' ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'tag', '${_IMAGE_NAME}', '${_IMAGE_LATEST}' ]
    id: 'tag-latest'
    waitFor: [ 'push-image' ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', '${_IMAGE_LATEST}' ]
    id: 'push-latest'
    waitFor: [ 'tag-latest' ]

options:
  dynamicSubstitutions: true

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/APP_TOKEN/versions/latest
      env: 'APP_TOKEN'
    - versionName: projects/$PROJECT_ID/secrets/CLIENT_ID/versions/latest
      env: 'CLIENT_ID'
    - versionName: projects/$PROJECT_ID/secrets/GUILD_ID/versions/latest
      env: 'GUILD_ID'
    - versionName: projects/$PROJECT_ID/secrets/PROXY_URL/versions/latest
      env: 'PROXY_URL'
