timeout: 1800s

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/discord-bot:$TAG_NAME',
      '--build-arg', 'APP_TOKEN=${_APP_TOKEN}',
      '--build-arg', 'CLIENT_ID=${_CLIENT_ID}',
      '--build-arg', 'GUILD_ID=${_GUILD_ID}',
      '.'
    ]
    secretEnv: ['_APP_TOKEN', '_CLIENT_ID', '_GUILD_ID']
    id: 'build-image'
    timeout: 600s

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/discord-bot:$TAG_NAME']
    id: 'push-image'
    timeout: 600s
    waitFor: ['build-image']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['tag', 'gcr.io/$PROJECT_ID/discord-bot:$TAG_NAME', 'gcr.io/$PROJECT_ID/discord-bot:latest']
    id: 'tag-latest'
    waitFor: ['push-image']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/discord-bot:latest']
    id: 'push-latest'
    waitFor: ['tag-latest']

images:
  - 'gcr.io/$PROJECT_ID/discord-bot:$TAG_NAME'
  - 'gcr.io/$PROJECT_ID/discord-bot:latest'

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/APP_TOKEN/versions/latest
      env: '_APP_TOKEN'
    - versionName: projects/$PROJECT_ID/secrets/CLIENT_ID/versions/latest
      env: '_CLIENT_ID'
    - versionName: projects/$PROJECT_ID/secrets/GUILD_ID/versions/latest
      env: '_GUILD_ID'
